services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bimbel-prod
    container_name: laravel12-app
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "9000:80"
    # environment:
    #   APP_ENV: production
    #   APP_DEBUG: "false"
    #   APP_KEY: base64:your-app-key-here
    #   DB_HOST: db
    #   DB_PORT: 3306
    #   DB_DATABASE: laravel
    #   DB_USERNAME: laravel
    #   DB_PASSWORD: secret
    # volumes:
    #   - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel

  # web:
  #   image: nginx:1.25-alpine
  #   container_name: nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - .:/var/www/html
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - app
  #   networks:
  #     - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge
