services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bimbel-prod
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "9000:80"
    depends_on:
      - mysql
    volumes:
      - app_data:/var/www/html/storage
    networks:
      - laravel
    deploy:
      resources:
        limits:
          memory: 128M

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - db_data:/var/lib/mysql
      # - ./docker/mysql:/etc/mysql/conf.d
    networks:
      - laravel

volumes:
  db_data:
  app_data:

networks:
  laravel:
    driver: bridge
